dbt_data:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_CONTAINER_NAME') }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      port: 8123
      schema: "{{ env_var('CLICKHOUSE_DW_DB') }}"