dbt_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: finpro-postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DW_DB') }}"
      schema: public
      threads: 4
