dbt_data:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: finpro-clickhouse-server
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      pass: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      port: 8123
      schema: "{{ env_var('CLICKHOUSE_DW_DB') }}"
