version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: ${CLICKHOUSE_CONTAINER_NAME}
    networks:
      - finpro-network
    restart: always
    ports:
      - ${CLICKHOUSE_HTTP_PORT}:8123  # HTTP interface
      - ${CLICKHOUSE_TCP_PORT}:9000  # Native TCP interface
    volumes:
      - ../clickhouse:/var/lib/clickhouse
      - ../clickhouse/config/config.xml:/etc/clickhouse-server/config.xml
      - ../clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DW_DB}
    ulimits:
      nofile:
          soft: 262144
          hard: 262144
    entrypoint: ["/bin/bash", "-c", "/var/lib/clickhouse/user_scripts/init.sh"]

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: ${TABIX_CONTAINER_NAME}
    networks:
      - finpro-network
    restart: always
    ports:
      - ${TABIX_PORT}:80  # Tabix Web UI
    depends_on:
      - clickhouse-server

networks:
  finpro-network:
    driver: bridge
    external: true