services:
  finpro-postgres:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_CONTAINER_NAME}
    networks:
      - finpro-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_AIRFLOW_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Jakarta
    volumes:
      - ../postgres/config/postgres.config:/var/lib/postgresql/data/postgresql.conf
      - ../postgres/data:/seeding/data
      - ../postgres/ecommerce-ddl.sql:/seeding/ecommerce-ddl.sql
      - ../postgres/ingest.sql:/seeding/ingest.sql
      - ../postgres/tables-ddl.sql:/seeding/tables-ddl.sql
      - ../postgres/script/init-permissions.sh:/docker-entrypoint-initdb.d/init-permissions.sh
    ports:
      - ${POSTGRES_PORT}:5432
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-permissions.sh"]
        
networks: 
  finpro-network:
    driver: bridge
    external: true
