views:
  - name: customer_metrics
    cubes:
      - join_path: dim_customers
        includes:
          - name: n_of_customers
            alias: "Number of Accounts"
          - name: n_of_users
            alias: "Number of Users"

          - name: city
            alias: "City"
          - name: state
            alias: "State"
          - name: account_id
            alias: "Account ID"
          - name: user_id
            alias: "User ID"

      - join_path: dim_customers.fct_orders
        includes:
          - name: avg_order_value
            alias: "Average Order Value"
          - name: order_count
            alias: "Count of Orders"
          - name: completed_order_count
            alias: "Count of Completed Orders"
          - name: canceled_order_count
            alias: "Count of Canceled Orders"
          - name: max_order_value
            alias: "Maximum Order Value"
          - name: min_order_value
            alias: "Minimum Order Value"
          - name: first_order_date
            alias: "First Order Date"
          - name: latest_order_date
            alias: "Latest Order Date"

      - join_path: dim_customers.fct_order_payments
        includes:
          - name: sum_payment_value
            alias: "Customer Lifetime Value"
      
      - join_path: dim_customers.fct_order_reviews
        includes: 
          - name: average_review_score
            alias: "Average Review Score"
          - name: count_reviews
            alias: "Number of Reviews"

      - join_path: dim_customers.fct_order_items
        includes:
          - name: count_distinct_product
            alias: "Number of Unique Products Bought"
          - name: sum_product_quantity
            alias: "Number of Products Bought"

  - name: seller_metrics
    cubes:
      - join_path: dim_sellers
        includes:
          - name: n_of_sellers
            alias: "Number of Sellers"

          - name: city
            alias: "City"
          - name: state
            alias: "State"
          - name: seller_id
            alias: "Seller ID"
      
      - join_path: dim_sellers.fct_orders
        includes:
          - name: avg_order_value
            alias: "Average Order Value"
          - name: order_count
            alias: "Count of Orders"
          - name: completed_order_count
            alias: "Count of Completed Orders"
          - name: canceled_order_count
            alias: "Count of Canceled Orders"
          - name: gmv
            alias: "Gross Merchandise Value (GMV)"
          - name: max_order_value
            alias: "Maximum Order Value"
          - name: min_order_value
            alias: "Minimum Order Value"
          - name: first_order_date
            alias: "First Order Date"
          - name: latest_order_date
            alias: "Latest Order Date"
          - name: active_user_count
            alias: "Number of Served Customers"

      - join_path: dim_sellers.fct_order_reviews
        includes: 
          - name: average_review_score
            alias: "Average Review Score"
          - name: count_reviews
            alias: "Number of Reviews"

      - join_path: fct_order_items
        includes:
          - name: count_distinct_product
            alias: "Number of Sold Unique Products"
          - name: sum_product_quantity   
            alias: "Number of Sold Products"   
