views:
  - name: customer_metrics
    cubes:
      - join_path: dim_customers
        includes:
          - name: n_of_customers
            alias: number_of_accounts
          - name: n_of_users
            alias: number_of_users

          - city
          - state
          - account_id
          - user_id

      - join_path: fct_orders
        includes:
          - avg_order_value
          - order_count
          - completed_order_count
          - canceled_order_count
          - max_order_value
          - min_order_value
          - first_order_date
          - latest_order_date

      - join_path: fct_order_payments
        includes:
          - name: sum_payment_value
            alias: lifetime_value
      
      - join_path: fct_order_reviews
        includes: 
          - name: average_review_score
            alias: avg_review_score
          - name: count_reviews
            alias: review_count

      - join_path: fct_order_items
        includes:
          - name: count_distinct_product
            alias: number_of_unique_products_bought
          - name: sum_product_quantity
            alias: number_of_products_bought

  - name: seller_metrics
    cubes:
      - join_path: dim_sellers
        includes:
          - name: n_of_sellers
            alias: number_of_sellers

          - city
          - state
          - seller_id
      
      - join_path: fct_orders
        includes:
          - avg_order_value
          - order_count
          - completed_order_count
          - canceled_order_count
          - name: gmv
            alias: gross_merchandise_value
          - max_order_value
          - min_order_value
          - first_order_date
          - latest_order_date
          - name: active_user_count
            alias: number_of_served_customers

      - join_path: fct_order_reviews
        includes: 
          - name: average_review_score
            alias: avg_review_score
          - name: count_reviews
            alias: review_count

      - join_path: fct_order_items
        includes:
          - name: count_distinct_product
            alias: number_of_unique_products_sold
          - name: sum_product_quantity   
            alias: number_of_sold_products   
