views:
  - name: number_of_leads
    
    cubes:
      - join_path: fct_lead_conversions
        includes:
          - n_of_leads

          - landing_page_id
          - first_contact_date
          
      - join_path: fct_lead_conversions.dim_leads
        includes:
          - status
          - channel